### ISSUE TITLE
Task and Reminder for the users

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#14]
As a syllabus manager, I should be able to give task to update , edit or review the syllabus to  user expert, reviewer , approver and normal user. I can give deadline to the task and alert the particular user  automatically once deadline is crossed and remind the user before the deadline.

**Comment by asiiim** [comment]
@bishalgit Iam planning to use and test project module for this issue.

**Comment by asiiim** [comment]
As more information is not needed as in the project task model, so I will create new model called "Syllabus_Task" for the above issue.

**Comment by asiiim** [comment]
To Do's
- Need to provide task type such as:
Review,
Approve,
Edit
- Need to provide task status such as:
Ongoing,
Completed
- Need to warn if deadline reach before certain days
- Need to send notification to the assignee
