### ISSUE TITLE
Old version of syllabus

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#15]
As syllabus is edited. System should track the older version separately with view and pdf option.
For eg: Syllabus: Business Mathematics I
First version : 2009
Second version : 2014
Third version : 2018 (Current version)

It means the previous two version should also be availalbe under the same course/sylabus which should be shareable and printable.

**Comment by asiiim** [comment]
@pdldeepak there is syllabus history where user can view and access and even print that previous version of the syllabus as per the above requirement.
We can provide button in syllabus history tree view which can print that syllabus of that version.

**Comment by pdldeepak** [comment]
-version convention on the system
-different version of the syllabus of same course can be linked to same faculty and semester
-able to download different version of the syllabus from report section (eg: Reports > Select Syllabus> Select version > Download PDF

**Comment by asiiim** [comment]
Todo

1. Providing convention of the syllabus versioning such that, latest version is of syllabus model and other previous versions of syllabus history model.
2. The syllabus history objects should be kept in courseline model as "old_syllabus_id" field.
3. There should be a boolean in courseline model such if true, can select "syllabus_id" field else can select "old_syllabus_id" field. Let that boolean be called "latest_syllabus".
4. There should be button for each object in syllabus history tree view inside of syllabus form view which can print that specific version of syllabus history of that syllabus.
5. About convention, let there be a field called "version" in syllabus and syllabus_history model which contains the unique version number for the syllabus.

**Comment by asiiim** [comment]
@bishalgit @Siddhant-Pageni Guys, help needed, discussion required for this issue.
Matter is, the latest version of syllabus is in "document.page" model and previous other versions in "document.page.history" model. In Program form view, there is a tab where we create objects for courseline models such that there is field for semester, course and syllabus. But if we need to add syllabus of old versions, there would be two fields i.e syllabus and old_syllbus, where we can select on 1 syllabus for each course in courseline model. So need discussion in this matter.

**Comment by bishalgit** [comment]
Use page history ids for this issue.
