### ISSUE TITLE
Syllabus Report & Packaging

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#16]
As a syllabus manager, I should be able to retrive the syllabus in pdf version

1. Individually
2. Faculty wise
3.Program wise
4.Semester wise of that particular program

It's all about packaging and as a user I should be able to retrive , view and print it very easily.

**Comment by asiiim** [comment]
We can use courseline model as it has link to faculty, program, level, semester and syllabus. We can create new section called Report using this model.

**Comment by pdldeepak** [comment]
-Reports > Select/Search Syllabus>View & Download PDF
-Reports>Select Faculty > View & Download Syllabus
-Reports > Select Faculty > Select Program > View & Download Syllabus
-Reports > Select Faculty > Select Program >Select Semester > View & Download Syllabus
