### ISSUE TITLE
Filter course, syllabus, faculty and programs effectively

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#17]
As a user, I should be able to search  the following data on 

- Syllabus
-Course
-Program
-Level (Bachelor, Master or Phd)
-Faculty

very easily on it's respective section.

For eg: I go to the menu course > then i should be able to filter the course level wise, program wise , faculty wise using group(filter option available on the system).

**Comment by jharna3991** [comment]
There is no relation to program in syllabus model as syllabus is independent to program so we cannot search syllabus on the basis of program and level too @pdldeepak

**Comment by asiiim** [comment]
It is meant to search in program list not in syllabus list.
We can search on the basis of course, level, and faculty.
Need to create new field called "level" in program model.
In case of course and syllabus, need to take from courseline model which is linked with program as
courseline_ids.
