### ISSUE TITLE
Filter syllabus list in courseline such that only the syllabus of the related course is seen for selection.

### ISSUE THREAD

**Issue by asiiim** [bishalgit/knowledge-syllabus#25]

**Comment by asiiim** [comment]
@bishalgit @Siddhant-Pageni , i could not filter the syllabus list in courseline tree view on the basis of the course selected in the same row. what may be the effective approach to counter this issue?

**Comment by jharna3991** [comment]
26eb35fbcf9d9aa0148a4a8aa0246ff3326f5283 
9b9c5f030bea1a9d07cdfad3ed827c3c1c1e091b
This issue is solved as referenced in above commits.
