### ISSUE TITLE
Syllabus Report : Empty field should not be shown while printing or generating syllabus

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#35]
On creating a syllabus, I am able to write the content of syllabus on different heading. If a user emptied the field then the title of the field should not be shown in the syllabus report in viewing or printing.
[Document Page (7).pdf](https://github.com/bishalgit/knowledge-syllabus/files/2546819/Document.Page.7.pdf)

**Comment by asiiim** [comment]
@jharna3991, provide condition for every field in data.xml field of the syllabus_template module such that, if that field has content than only provide to do t-esc else not.
