### ISSUE TITLE
Approve button is hidden on clicking the change request for approving the syllabus

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#41]

**Comment by asiiim** [comment]
Please elaborate !

**Comment by pdldeepak** [comment]
As the syllabus is updated, it is gone to an approver for syllabus approver as change request. Once user click on change request, the following window doesnot give an option to approve the syllabus.(Approve tab on top).

Previously there was a button, but now i am not able to see it.

Please check it once from your side as well.

**Comment by asiiim** [comment]
But i find okay in live one.
