### ISSUE TITLE
Reports Refining: Curriculum Report and Syllabus Report

### ISSUE THREAD

**Issue by pdldeepak** [bishalgit/knowledge-syllabus#46]
1. Spacing between Heading of following title and Content of previous heading (1.0)

2. Default font content size: 12 Default Font : Times New Roman 

3.What if the Only the Title remain in the last line of a page. Please push it down if such case happens.

4.Page Margin: Normal :  Top:1" Bottom" 1" Left: 1" and Right: 1"

**Comment by pdldeepak** [comment]
@jharna3991 @ashimbajracharya

**Comment by pdldeepak** [comment]
1.The title of the program and it's code should be on the same line enclosed with small bracket.

**Comment by asiiim** [comment]
@pdldeepak incase of point number 3, this is not issue because in case of MS Word, if the content exceeds in the certain page, the title gets reside in the same page even though the content goes to the next page.

**Comment by pdldeepak** [comment]
@ashimbajracharya In MS-Word, we have the option to manually push it down. As of now, we don't have any such system so what could be the best option to address this situation.

For eg: 1500 syllabus may have 1000 syllabus with this problem shows the universities unprofessionalism in managing the syllabus.We may not know on what situation this problem arises.




1.Aren't we able to track the line of a document page? If so, that would be the best solution.
